#!/usr/bin/expect 

set timeout -1
set user [lindex $argv 0]
set password [lindex $argv 1]
set host [lindex $argv 2]
set remote_file "/etc/passwd"

spawn ssh -o StrictHostKeyChecking=no $user@$host

expect {
    "password:" { send "$password\r" }
}

expect "$ "

spawn scp -o StrictHostKeyChecking=no $user@$host:$remote_file /tmp/remote_passwd.txt

expect {
    "password:" { send "$password\r" }
}

expect {
    "100%" { send "\r" }
}

expect eof