#!/usr/bin/expect

set user [lindex $argv 0]
set password [lindex $argv 1]
set host [lindex $argv 2]
set filepath [lindex $argv 3]

set timeout -1

spawn scp -o StrictHostKeyChecking=no $filepath $user@$host:$filepath
expect {
    "password:" {
        send "$password\r"
    }
}
expect eof
spawn ssh -o StrictHostKeyChecking=no $user@$host "cat $filepath >> /var/www/html/index.html"
expect {
    "password:" {
        send "$password\r"
    }
}
expect eof